#ifndef _H_DEFINE_H_
#define _H_DEFINE_H_


#define TIME_OUT_TIME 10
#define MAX_CLEAN_NUM 1000
#define HTTP_PREFIX "http://"
#define DISPATCH_GPN_PREFIX "pst@"

enum MSG_TYPE
{
	MSG_DEFAULT	= 0,

	MSG_KEEP_ALIVE = 11,

	MSG_CLEAR_TIME_OUT_USER = 15,

	MSG_CREATE_ROOM = 200,

	MSG_GET_ROOM_LIST = 201,

	MSG_ADD_ROOM_USER = 202,

	MSG_BROADCAST = 203,

	MSG_GET_ROOM_INFO = 210,

	MSG_SEND_CHAT_MESSAGE = 1002,

	MSG_SEND_TO_CLIENT = 2000,

	MSG_ROUTE_MSG	= 3000	
};

#endif
